//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C0NE_TIME_SCRIPT_EVENTS
    {
        public string ScriptID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime AppliedOn { get; set; }
        public string Comments { get; set; }
    }
}
