//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTRUC_SIS
    {
        public string Nom_org { get; set; }
        public string Dir_org { get; set; }
        public string tlf_org { get; set; }
        public string loc_org { get; set; }
        public string Rif_org { get; set; }
        public string Nit_org { get; set; }
        public string Ser_sof { get; set; }
        public string Key_Sof { get; set; }
        public double CR_FISCAL { get; set; }
        public string CU_SIGLAS { get; set; }
        public string Alias { get; set; }
        public string Pais { get; set; }
        public string Estado { get; set; }
        public string Ciudad { get; set; }
    }
}
