//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_AVANCE_EFECTIVO
    {
        public string c_Caja { get; set; }
        public string c_Documento { get; set; }
        public double Turno { get; set; }
        public string c_Concepto { get; set; }
        public System.DateTime f_Fecha { get; set; }
        public System.DateTime f_Hora { get; set; }
        public string c_Usuario { get; set; }
        public string c_Cliente { get; set; }
        public double n_Subtotal { get; set; }
        public double n_Impuesto { get; set; }
        public double n_Total { get; set; }
        public int n_Transacciones { get; set; }
        public string c_Sucursal { get; set; }
        public string c_Numero_Rel { get; set; }
        public decimal ID { get; set; }
    }
}
