//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_AVANCE_EFECTIVO_DETPAG
    {
        public string c_Caja { get; set; }
        public string c_Documento { get; set; }
        public string c_CodMoneda { get; set; }
        public string c_CodDenominacion { get; set; }
        public double n_Factor { get; set; }
        public System.DateTime d_Fecha { get; set; }
        public string c_CodBanco { get; set; }
        public string c_Banco { get; set; }
        public string c_Referencia { get; set; }
        public double n_Monto { get; set; }
        public string c_CodCajero { get; set; }
        public string c_Localidad { get; set; }
        public double Turno { get; set; }
        public string c_Util { get; set; }
        public Nullable<decimal> RelacionDetPag { get; set; }
        public decimal ID { get; set; }
    }
}
