//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ACTUALIZACION_INVENTARIO_PENDIENTE
    {
        public string cs_codcaja { get; set; }
        public string cs_codcajero { get; set; }
        public string cs_descripcioncajero { get; set; }
        public string cs_codlocalidad { get; set; }
        public string ns_turno { get; set; }
        public string cs_codusuario { get; set; }
        public System.DateTime ds_fechacierre { get; set; }
        public System.DateTime ds_fechafallo { get; set; }
    }
}
