//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BLACKSTONE_PREPAID_ORDERS
    {
        public string StellarOrderID { get; set; }
        public string TicketNumber { get; set; }
        public int ServiceType { get; set; }
        public int Status { get; set; }
        public int ID { get; set; }
    }
}
