//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_BOTONES_CAJA
    {
        public string CS_CAJA { get; set; }
        public string CS_PERFIL { get; set; }
        public string CS_BOTON_CODIGO { get; set; }
        public string CU_TIPO_BOTON { get; set; }
        public int NU_POSICION { get; set; }
        public string CU_DATO { get; set; }
        public string CU_FUENTE { get; set; }
        public bool CU_BOLD { get; set; }
        public bool CU_ITALIC { get; set; }
        public bool CU_STRIKE { get; set; }
        public bool CU_UNDERLINE { get; set; }
        public int NU_TAMANO { get; set; }
        public byte[] IU_IMAGE { get; set; }
        public System.DateTime FS_FECHA_HORA { get; set; }
        public string CS_RELACION { get; set; }
        public int CU_TECLA_HOT { get; set; }
        public int CU_TECLA { get; set; }
        public decimal ID { get; set; }
    }
}
