//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAMBIOS
    {
        public string C_DOCUMENTO { get; set; }
        public System.DateTime F_FECHA { get; set; }
        public string C_CODLOCALIDAD { get; set; }
        public string C_OBSERVACION { get; set; }
        public string C_CONCEPTO { get; set; }
        public string C_EMISOR { get; set; }
    }
}
