//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAJA_PARAMETROS
    {
        public int ID { get; set; }
        public string IDGrupoConfiguracion { get; set; }
        public string cCodigoCaja { get; set; }
        public string cSeccionIni { get; set; }
        public string cVariableIni { get; set; }
        public string cValor { get; set; }
        public bool bActivo { get; set; }
        public string cDefaultValue { get; set; }
    }
}
