//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAJA
    {
        public string C_Codigo { get; set; }
        public string C_Desc_Caja { get; set; }
        public string C_relacion { get; set; }
        public bool Bayuda { get; set; }
        public bool Cayuda { get; set; }
        public int Nayuda { get; set; }
        public bool Blimite { get; set; }
        public bool Climite { get; set; }
        public int Nlimite { get; set; }
        public bool Bproductos { get; set; }
        public bool Cproductos { get; set; }
        public int Nproductos { get; set; }
        public bool Bcantidad { get; set; }
        public bool Ccantidad { get; set; }
        public int Ncantidad { get; set; }
        public bool Bbalanza { get; set; }
        public bool Cbalanza { get; set; }
        public int Nbalanza { get; set; }
        public bool Breintegro { get; set; }
        public bool Creintegro { get; set; }
        public int Nreintegro { get; set; }
        public bool Bparcial { get; set; }
        public bool Cparcial { get; set; }
        public int Nparcial { get; set; }
        public bool Bespera { get; set; }
        public bool Cespera { get; set; }
        public int Nespera { get; set; }
        public bool Bsuspender { get; set; }
        public bool Csuspender { get; set; }
        public int Nsuspender { get; set; }
        public bool Bdevolucion { get; set; }
        public bool Cdevolucion { get; set; }
        public int Ndevolucion { get; set; }
        public bool Bprecios { get; set; }
        public bool Cprecios { get; set; }
        public int Nprecios { get; set; }
        public bool Bcliente { get; set; }
        public bool Ccliente { get; set; }
        public int Ncliente { get; set; }
        public int NCierre { get; set; }
        public int Gabeta { get; set; }
        public bool Gserial { get; set; }
        public string Gpuerto { get; set; }
        public string Gbaudios { get; set; }
        public string Gparidad { get; set; }
        public int Gbit { get; set; }
        public double Gparada { get; set; }
        public string Gcontrol { get; set; }
        public int Balanza { get; set; }
        public string Bpuerto { get; set; }
        public string Bbaudios { get; set; }
        public string Bparidad { get; set; }
        public int Bbit { get; set; }
        public double Bparada { get; set; }
        public string Bcontrol { get; set; }
        public int Scanner { get; set; }
        public string Spuerto { get; set; }
        public string Sbaudios { get; set; }
        public string Sparidad { get; set; }
        public int Sbit { get; set; }
        public double Sparada { get; set; }
        public string Scontrol { get; set; }
        public int Display { get; set; }
        public string Dpuerto { get; set; }
        public string Dbaudios { get; set; }
        public string Dparidad { get; set; }
        public int Dbit { get; set; }
        public double Dparada { get; set; }
        public bool Imp_ordenada { get; set; }
        public bool Imp_agrupada { get; set; }
        public bool Imp_LxL { get; set; }
        public bool COpenpos { get; set; }
        public int NOpenpos { get; set; }
        public bool CClosepos { get; set; }
        public int NClosepos { get; set; }
        public string Mensaje1 { get; set; }
        public string Mensaje2 { get; set; }
        public string Mensaje3 { get; set; }
        public string Mensaje4 { get; set; }
        public string Mensaje5 { get; set; }
        public int Dno_lineas { get; set; }
        public int Dca_lineas { get; set; }
        public int Impresora { get; set; }
        public string IPuerto { get; set; }
        public string Ibaudios { get; set; }
        public string Iparidad { get; set; }
        public int Ibit { get; set; }
        public double Iparada { get; set; }
        public double NO_CIERRES { get; set; }
        public bool Dato_string { get; set; }
        public bool Forma_continua { get; set; }
        public int no_lineas { get; set; }
        public bool ihojilla { get; set; }
        public string hojilla_caracter { get; set; }
        public bool imp_incluido { get; set; }
        public string C_CODDEPOSITO { get; set; }
        public string C_CODLOCALIDAD { get; set; }
        public string C_CODMONEDA { get; set; }
        public bool B_SOLICITAR_FONDO { get; set; }
        public bool B_POS_DIGITAL { get; set; }
        public bool B_OPOS { get; set; }
        public string C_OPOSD { get; set; }
        public string C_OPOSG { get; set; }
        public string C_OPOSS { get; set; }
        public string C_OPOSBA { get; set; }
        public string C_OPOSB { get; set; }
        public string C_OPOSL { get; set; }
        public string C_OPOSI { get; set; }
        public string C_OPOST { get; set; }
        public int banda { get; set; }
        public string bmpuerto { get; set; }
        public string bmbaudios { get; set; }
        public string bmparidad { get; set; }
        public int bmbit { get; set; }
        public double bmparada { get; set; }
        public bool llaves { get; set; }
        public bool imp_cheques { get; set; }
        public int rotacion { get; set; }
        public int LAYUDA { get; set; }
        public int LPRODUCTOS { get; set; }
        public int LLIMITE { get; set; }
        public int LCANTIDAD { get; set; }
        public int LBALANZA { get; set; }
        public int LREINTEGRO { get; set; }
        public int LESPERA { get; set; }
        public int LSUSPENDER { get; set; }
        public int LDEVOLUCION { get; set; }
        public int LPRECIOS { get; set; }
        public int LCLIENTE { get; set; }
        public int LCERRAR { get; set; }
        public int LPARCIAL { get; set; }
        public double tiempovuelto { get; set; }
        public int n_transacciones { get; set; }
        public bool b_ventas_volumen { get; set; }
        public string cs_formatoFactura { get; set; }
        public string cs_formatoDevolucion { get; set; }
        public string cs_formatoReintegro { get; set; }
        public string cs_formatoEspera { get; set; }
        public bool bs_FacturaPuerto { get; set; }
        public bool bs_DevolucionPuerto { get; set; }
        public bool bs_ReintegroPuerto { get; set; }
        public bool bs_EsperaPuerto { get; set; }
        public bool B_POS_PEDIDO { get; set; }
        public bool bu_administra_clientes { get; set; }
        public bool bu_AUTODECLARACION { get; set; }
        public bool bu_CHEQUE_POR_PUERTO { get; set; }
        public bool bu_LLEVAR_LOCAL { get; set; }
        public bool bu_COMANDA_REMOTA { get; set; }
        public int bu_ESSHELL { get; set; }
        public bool bu_COMANDA_LOCAL { get; set; }
        public bool bu_LLEVAR_REMOTA { get; set; }
        public bool bu_POR_PUERTO { get; set; }
        public bool CU_PREGUNTAR_IMPRIMIR_FACTURA { get; set; }
        public string CU_IMPRESORA_FACTURAR { get; set; }
        public string CU_IMPRESORA_CHEQUE { get; set; }
        public Nullable<System.DateTime> fu_hora_cierre { get; set; }
        public Nullable<System.DateTime> fu_hora_cierre_max { get; set; }
        public int nu_campo_busqueda { get; set; }
        public int nu_maximo_consumo_imprimir { get; set; }
        public int nu_tipo_precio { get; set; }
        public string Observaciones { get; set; }
        public bool bs_ImpresoraFiscal { get; set; }
        public string cs_SerialFiscal { get; set; }
    }
}
