//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CIERRExFACTURA
    {
        public string CU_CODCAJA { get; set; }
        public string CU_NUMFACTURA { get; set; }
        public string CU_NUMCIERRE { get; set; }
        public string CU_CODCAJEROPOS { get; set; }
        public string CU_CONCEPTO { get; set; }
        public decimal ID { get; set; }
    }
}
