//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAJA_BITACORA
    {
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_CAJA { get; set; }
        public decimal ns_TURNO { get; set; }
        public string cs_ESTADO { get; set; }
        public System.DateTime ds_FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> ds_FECHA_CIERRE { get; set; }
        public string cs_CAJERO { get; set; }
        public string cs_NOMBRE_CAJERO { get; set; }
        public int ns_NUMERO_OPERACIONES { get; set; }
        public double ns_MONTO_VENDIDO { get; set; }
        public int ns_NUMERO_DEVOLUCIONES { get; set; }
        public double ns_MONTO_DEVUELTO { get; set; }
        public int nu_REINTEGROS_TOTALES { get; set; }
        public double nu_MONTOREINTEGRO_TOTAL { get; set; }
        public double nu_monto_retiros { get; set; }
        public int ns_CORTES { get; set; }
        public double ns_SUSPENDIDO { get; set; }
        public bool bs_INVENTARIO { get; set; }
        public decimal ID { get; set; }
        public double nu_MONTO_RETIROS1 { get; set; }
        public string EQUIPO { get; set; }
        public string VERSION { get; set; }
    }
}
