//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONSECUTIVOS
    {
        public string Facturas { get; set; }
        public string Reintegro { get; set; }
        public string Espera { get; set; }
        public string Devolucion { get; set; }
        public string cierre_par { get; set; }
        public string cierre_tot { get; set; }
        public string deposito { get; set; }
        public string cierre_caja_tot { get; set; }
        public string cambios { get; set; }
        public int ORG_CAJA { get; set; }
        public double POS { get; set; }
        public decimal turnos { get; set; }
        public decimal n_volumen { get; set; }
        public decimal FacturaxCierre { get; set; }
        public decimal DevolucionesxCierre { get; set; }
    }
}
