//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONSUMO
    {
        public string cs_CODIGOSERVICIO { get; set; }
        public string cs_CODIGOCUENTA { get; set; }
        public string cs_CODIGOMESA { get; set; }
        public string cs_RELACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_ORGANIZACION { get; set; }
        public string cu_CODIGOCLIENTE { get; set; }
        public string cu_NOMBRECLIENTE { get; set; }
        public string cu_RIFCLIENTE { get; set; }
        public string cu_DIRECCION_CLIENTE { get; set; }
        public string cu_TELEFONO_CLIENTE { get; set; }
        public string cu_observacion { get; set; }
        public string cs_CODIGOMESERO { get; set; }
        public double ns_SUBTOTAL { get; set; }
        public double ns_IMPUESTOS { get; set; }
        public double ns_TOTAL { get; set; }
        public string cs_MONEDA_PREFERENCIAL { get; set; }
        public double ns_FACTOR_PREFERENCIAL { get; set; }
        public string cs_PRECIOCLIENTE { get; set; }
        public bool bs_CONSOLIDADA { get; set; }
        public bool bs_REINTEGRADA { get; set; }
        public string cs_CODIGO_AUTORIZA { get; set; }
        public int ns_NIVEL_AUTORIZA { get; set; }
        public System.DateTime fs_FECHA_REINTEGRO { get; set; }
        public System.DateTime fs_FECHA_HORA { get; set; }
        public double ns_monto_limite { get; set; }
        public int ns_notas_impresas { get; set; }
        public string cu_direccion_despacho { get; set; }
        public int EstatusKDS { get; set; }
        public string cs_Repartidor { get; set; }
        public int ns_TipoServicio { get; set; }
        public string ns_Estatus_Entrega { get; set; }
        public System.DateTime ds_FechaHora_Entrega { get; set; }
        public bool bs_Impresa { get; set; }
        public string c_Observacion { get; set; }
    }
}
