//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAJA_BOTONES_DIGITALES_PERFIL
    {
        public string CodigoPerfil { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime HoraIni { get; set; }
        public System.DateTime HoraFin { get; set; }
        public int Dias { get; set; }
    }
}
