//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CAJA_BOTONES
    {
        public int POSICION { get; set; }
        public string NOMBRE { get; set; }
        public int TECLA { get; set; }
        public int SHIFT { get; set; }
        public int TIPOPOS { get; set; }
        public bool BNIVEL { get; set; }
        public bool BLLAVE { get; set; }
        public bool BACTIVO { get; set; }
        public bool BDEFAULT { get; set; }
        public string COMENTARIO { get; set; }
        public int ResourceID { get; set; }
        public decimal ID { get; set; }
    }
}
