//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CIERRE_POS_TOTAL
    {
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_DOCUMENTO { get; set; }
        public System.DateTime ds_FECHA { get; set; }
        public string cs_CAJA { get; set; }
        public decimal cs_TURNO { get; set; }
        public System.DateTime ds_FECHA_INICIO_TURNO { get; set; }
        public System.DateTime ds_FECHA_FINAL_TURNO { get; set; }
        public string cs_CAJERO { get; set; }
        public string cs_NOMBRE_CAJERO { get; set; }
        public string cs_USUARIO { get; set; }
        public double ns_NUMERO_OPERACIONES { get; set; }
        public int ns_NUMERO_REINTEGROS { get; set; }
        public double ns_MONTO_REINTEGROS { get; set; }
        public int ns_NUMERO_DEVOLUCION { get; set; }
        public double ns_MONTO_DEVOLUCION { get; set; }
        public double ns_MONTO_IMPUESTOS_DEVOLUCION { get; set; }
        public int ns_NUMERO_CORTES_PARCIALES { get; set; }
        public double ns_MONTO_CORTES_PARCIALES { get; set; }
        public string cs_MONEDA_PREFERENCIAL { get; set; }
        public double ns_FACTOR_MONEDA_PREFERENCIAL { get; set; }
        public double ns_MONTO_TOTAL { get; set; }
        public double ns_MONTO_CREDITOS { get; set; }
        public double ns_MONTO_SUBTOTAL { get; set; }
        public double ns_MONTO_IMPUESTO { get; set; }
        public double ns_SERVICIO { get; set; }
        public double ns_MONTO_DESCUENTO { get; set; }
        public double ns_MONTO_DECLARADO { get; set; }
        public string cs_OBSERVACION { get; set; }
        public double NS_MONTO_SERVICIO { get; set; }
    }
}
