//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CIERRES
    {
        public string c_DOCUMENTO { get; set; }
        public string c_CODCAJA { get; set; }
        public string c_CODCAJERO { get; set; }
        public string c_CODLOCALIDAD { get; set; }
        public string c_CONCEPTO { get; set; }
        public Nullable<System.DateTime> d_FECHA { get; set; }
        public Nullable<double> n_BSRECIBIDOS { get; set; }
        public Nullable<double> n_DIFERENCIA { get; set; }
        public string c_OBSERVACION { get; set; }
        public string c_CODUSUARIO { get; set; }
        public string c_des_cajera { get; set; }
        public Nullable<double> n_BSVENDIDO { get; set; }
        public Nullable<double> n_SUBTOTAL { get; set; }
        public Nullable<double> n_IMPUESTO { get; set; }
        public Nullable<double> n_CLIENTE { get; set; }
        public Nullable<System.DateTime> h_INICIO { get; set; }
        public Nullable<System.DateTime> h_FINAL { get; set; }
        public Nullable<int> n_reintegros { get; set; }
        public Nullable<int> n_devolucion { get; set; }
        public Nullable<double> n_montodevolucion { get; set; }
        public Nullable<int> n_cortesparciales { get; set; }
        public Nullable<double> n_montocortes { get; set; }
        public string c_num_cierre { get; set; }
        public double turno { get; set; }
        public Nullable<double> n_imp_devolucion { get; set; }
        public Nullable<System.DateTime> D_FECHA_CIERRE { get; set; }
        public double n_monto_reintegros { get; set; }
    }
}
