//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_CONCEPTOS
    {
        public decimal IDCONCEPTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal IDPROCESO { get; set; }
        public int DE_SISTEMA { get; set; }
        public string Documento { get; set; }
        public int Predeterminada { get; set; }
        public int nu_nivelusuario { get; set; }
        public bool bu_activo { get; set; }
        public bool bu_consideraimpuesto { get; set; }
        public bool bu_Conceptodeservicio { get; set; }
        public bool bu_ConsideraLibro { get; set; }
        public bool bu_ConceptoRetencion { get; set; }
        public bool bu_RequiereUnidad { get; set; }
        public bool bu_ConsolidarFactura { get; set; }
    }
}
