//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DISPOSITIVOS_CAJA
    {
        public string CAJA { get; set; }
        public string cs_CODIGODISPOSITIVO { get; set; }
        public string cu_PUERTO { get; set; }
        public string cu_BAUDIOS { get; set; }
        public string cu_PARIDAD { get; set; }
        public int cu_PARADA { get; set; }
        public int cu_BITDATOS { get; set; }
        public string cu_CARCONTROL { get; set; }
        public string cu_COMANDOSTR { get; set; }
        public string cu_CARCORTE { get; set; }
        public int cu_OPOS { get; set; }
        public string cu_NOMBREOPOS { get; set; }
        public int cu_ACTIVO { get; set; }
        public bool cu_IHOJILLA { get; set; }
        public bool cu_IMP_CHEQUES { get; set; }
        public int cu_ROTACION { get; set; }
    }
}
