//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DENOMINACIONES
    {
        public string c_codmoneda { get; set; }
        public string c_coddenomina { get; set; }
        public string c_denominacion { get; set; }
        public double n_valor { get; set; }
        public int c_real { get; set; }
        public double N_CANTIDAD { get; set; }
        public double N_BOLIVARES { get; set; }
        public double N_ENTRADO { get; set; }
        public double N_FACTOR { get; set; }
    }
}
