//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DOCUMENTOS_FISCAL
    {
        public string cu_DocumentoStellar { get; set; }
        public string cu_DocumentoFiscal { get; set; }
        public string cu_DocumentoTipo { get; set; }
        public string cu_Localidad { get; set; }
        public string cu_SerialImpresora { get; set; }
        public string cu_ZFiscal { get; set; }
    }
}
