//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DEPOSITOS
    {
        public string C_DOCUMENTO { get; set; }
        public System.DateTime D_FECHA { get; set; }
        public string C_CODLOCALIDAD { get; set; }
        public string C_CODBANCO { get; set; }
        public string C_CUENTA { get; set; }
        public string C_PLANILLA { get; set; }
        public string C_CATAPORTE { get; set; }
        public double N_BSRECIBIDOS { get; set; }
        public string C_CODUSUARIO { get; set; }
        public string c_num_cierre { get; set; }
        public Nullable<int> C_CERRADO { get; set; }
    }
}
