//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_DEVOLUCION
    {
        public string C_Numero { get; set; }
        public System.DateTime F_Fecha { get; set; }
        public Nullable<System.DateTime> F_Hora { get; set; }
        public string C_Cliente { get; set; }
        public Nullable<double> N_Cancelado { get; set; }
        public string C_Sucursal { get; set; }
        public string C_Caja { get; set; }
        public string C_Usuario { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public Nullable<double> Total { get; set; }
        public string N_Factura { get; set; }
        public string c_util { get; set; }
    }
}
