//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ETIQUETAS
    {
        public string C_CODIGO { get; set; }
        public string C_DESCRIPCIO { get; set; }
        public string C_LONGITUD { get; set; }
        public double N_LONGITUD { get; set; }
        public int N_POS_INI_1 { get; set; }
        public int N_CARACTERES_1 { get; set; }
        public int C_CAMPO { get; set; }
        public int N_POS_INI_2 { get; set; }
        public int N_CARACTERES_2 { get; set; }
        public bool B_MANEJA_DECIMAL { get; set; }
        public int N_POS_INI_3 { get; set; }
        public int N_CARACTERES_3 { get; set; }
        public bool B_ACTIVA { get; set; }
        public bool B_VERIFICADIGITO { get; set; }
    }
}
