//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ERRORES
    {
        public string NUMERO { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA { get; set; }
        public string USUARIO { get; set; }
        public string MODULO { get; set; }
        public string FORMA { get; set; }
        public string OBJ_PRO_FUN { get; set; }
        public string EQUIPO { get; set; }
        public decimal ID { get; set; }
    }
}
