//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ESTRUC_CAJA
    {
        public string CLAVE { get; set; }
        public string TEXTO { get; set; }
        public string RELACION { get; set; }
        public byte[] Fondo { get; set; }
    }
}
