//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_HABLADORES_BITACORA
    {
        public decimal id { get; set; }
        public string Equipo { get; set; }
        public System.DateTime f_fechahora { get; set; }
        public string c_usuario { get; set; }
    }
}
