//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_IMPRESORA_GRUPO
    {
        public string cs_DEPARTAMENTO { get; set; }
        public string cs_GRUPO { get; set; }
        public string cu_IMPRESORA { get; set; }
        public string cs_RELACION { get; set; }
        public bool bu_POR_PUERTO { get; set; }
        public int nu_llevar { get; set; }
    }
}
