//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_KDS
    {
        public string cs_CODIGO { get; set; }
        public string KDS_ID { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public int FocusColor { get; set; }
        public int OrderColor { get; set; }
        public int ItemColor { get; set; }
        public int DeliveryColor { get; set; }
        public int ScreenColor { get; set; }
        public int BackColor { get; set; }
        public string cs_RELACION { get; set; }
        public string cs_DESCRIPCION { get; set; }
        public bool bu_por_puerto { get; set; }
        public int nu_llevar { get; set; }
        public int IDModeloCompatible { get; set; }
    }
}
