//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_MENSAJES
    {
        public string C_Codigo { get; set; }
        public string Mensaje1 { get; set; }
        public string Mensaje2 { get; set; }
        public string Mensaje3 { get; set; }
        public string Mensaje4 { get; set; }
        public string Mensaje5 { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string C5 { get; set; }
        public Nullable<System.DateTime> INIM1 { get; set; }
        public Nullable<System.DateTime> FINM1 { get; set; }
        public Nullable<System.DateTime> INIM2 { get; set; }
        public Nullable<System.DateTime> FINM2 { get; set; }
        public Nullable<System.DateTime> INIM3 { get; set; }
        public Nullable<System.DateTime> FINM3 { get; set; }
        public Nullable<System.DateTime> INIM4 { get; set; }
        public Nullable<System.DateTime> FINM4 { get; set; }
        public Nullable<System.DateTime> INIM5 { get; set; }
        public Nullable<System.DateTime> FINM5 { get; set; }
    }
}
