//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PRODUCTOS_COMPUESTOS
    {
        public string cs_CODIGO_PRODUCTO { get; set; }
        public double cu_CANTIDAD { get; set; }
        public string cu_CODIGO_PARTE { get; set; }
        public decimal ID { get; set; }
    }
}
