//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PAGOS_IMPUESTOS
    {
        public string c_Numero { get; set; }
        public string c_Concepto { get; set; }
        public string c_Localidad { get; set; }
        public double n_MontoBase { get; set; }
        public double n_PorcImp { get; set; }
        public double n_MontoImp { get; set; }
    }
}
