//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PAGOS
    {
        public string c_Caja { get; set; }
        public string c_Numero { get; set; }
        public System.DateTime f_Fecha { get; set; }
        public System.DateTime f_Hora { get; set; }
        public string c_Cliente { get; set; }
        public double n_Subtotal { get; set; }
        public double n_Impuesto { get; set; }
        public double n_Total { get; set; }
        public double n_Cancelado { get; set; }
        public double n_Vuelto { get; set; }
        public string c_Sucursal { get; set; }
        public string c_Usuario { get; set; }
        public double t_Venta { get; set; }
        public int n_Productos { get; set; }
        public string c_Concepto { get; set; }
        public string c_Desc_Cliente { get; set; }
        public string c_Rif { get; set; }
        public double n_BaseImp { get; set; }
        public double n_Descuento { get; set; }
        public double Turno { get; set; }
        public decimal ID { get; set; }
        public string cu_Direccion_Cliente { get; set; }
        public string cs_Numero_Bajada { get; set; }
        public bool bs_Impresa { get; set; }
        public bool bs_Contribuyente { get; set; }
        public string cs_Documento_Rel { get; set; }
        public string cs_NumBajada_Destino { get; set; }
    }
}
