//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PLATOS_GRUPOS
    {
        public decimal n_Codigo { get; set; }
        public decimal n_Plato { get; set; }
        public string c_Descripcion { get; set; }
        public decimal n_Cantidad { get; set; }
        public bool b_Requerido { get; set; }
        public bool b_Costeable { get; set; }
        public bool b_Sistema { get; set; }
    }
}
