//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PLATOS_GRUPOS_PRO
    {
        public decimal n_Grupo { get; set; }
        public decimal n_Plato { get; set; }
        public string c_Producto { get; set; }
        public decimal n_Cantidad { get; set; }
        public int n_Decimales { get; set; }
        public int n_Linea { get; set; }
        public decimal n_PrecioGrupo { get; set; }
    }
}
