//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_RET_CIE_CP
    {
        public string C_DOCUMENTO { get; set; }
        public string C_CODCAJERO { get; set; }
        public System.DateTime D_FECHA { get; set; }
        public double N_BSRECIBIDOS { get; set; }
        public double N_DEPOSITADO { get; set; }
        public double N_DIFERENCIA { get; set; }
        public string C_CONCEPTO { get; set; }
    }
}
