//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_REPORTES
    {
        public string cs_CODIGO_REPORTE { get; set; }
        public string cu_DESCRIPCION_REPORTE { get; set; }
        public string cu_SQL { get; set; }
        public System.DateTime cs_FECHA_CREADO { get; set; }
        public System.DateTime cs_FECHA_MODIFICADO { get; set; }
        public string cs_RUTA { get; set; }
        public string cs_RUTA_REMOTA { get; set; }
        public bool bu_POR_PUERTO { get; set; }
    }
}
