//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_SYSTABLAS
    {
        public string TABLA { get; set; }
        public string CAMPO { get; set; }
        public string TIPO { get; set; }
        public int LONGITUD { get; set; }
        public string VALOR { get; set; }
        public bool NULO { get; set; }
    }
}
