//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_SITIO
    {
        public string cs_CODIGOSITIO { get; set; }
        public string cs_CODIGORELACION { get; set; }
        public string cu_DESCRIPCION { get; set; }
        public int AxisX { get; set; }
        public int AxisY { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
    }
}
