//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_SORTEOS
    {
        public string TIPO { get; set; }
        public System.DateTime f_inicio { get; set; }
        public System.DateTime f_final { get; set; }
        public double condicion { get; set; }
        public int acumulado { get; set; }
        public string mensaje { get; set; }
        public string mensaje1 { get; set; }
        public string mensaje2 { get; set; }
        public bool mult_tickets { get; set; }
        public int BS_ACTIVO { get; set; }
        public int BS_AFILIADOS { get; set; }
        public bool bs_cumpleanos { get; set; }
        public string CS_CODIGO_SORTEO { get; set; }
        public double NU_MONTOMAXIMO { get; set; }
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public bool bs_imprimirtickets { get; set; }
        public int nu_tiposorteo { get; set; }
        public bool bs_acumula { get; set; }
        public bool bs_ImpPtosCompra { get; set; }
        public bool bs_ImpPtosAcumulados { get; set; }
        public int nu_tipoImpresionTickets { get; set; }
        public string cs_nombresorteo { get; set; }
        public bool bs_sorteocombinado { get; set; }
        public decimal nu_cantidadcombinada { get; set; }
        public decimal nu_valorcombinado { get; set; }
        public bool bs_sorteocombinado_montomin { get; set; }
        public string cs_grupocliente { get; set; }
        public bool AplicaLunes { get; set; }
        public bool AplicaMartes { get; set; }
        public bool AplicaMiercoles { get; set; }
        public bool AplicaJueves { get; set; }
        public bool AplicaViernes { get; set; }
        public bool AplicaSabado { get; set; }
        public bool AplicaDomingo { get; set; }
    }
}
