//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TABLAS_SYNCRONIZAR
    {
        public string cu_descripcion { get; set; }
        public string cu_mensaje { get; set; }
        public string cu_mensajeEliminar { get; set; }
        public string cu_tabla_maestra { get; set; }
        public string cu_campob_maestra { get; set; }
        public string cu_tabla_TR { get; set; }
        public string cu_campob_TR { get; set; }
        public string cu_tabla_tr_pend { get; set; }
        public string cu_campob_tr_pend { get; set; }
        public int nu_proceso { get; set; }
        public string cu_camposExepcion { get; set; }
        public string cu_camposExepcionTr { get; set; }
        public int cu_accion { get; set; }
        public int cu_nivel_prioridad { get; set; }
        public int cu_TIPO { get; set; }
        public decimal cu_codtablassyncronizar { get; set; }
    }
}
