//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_TRANSACCION
    {
        public string c_Numero { get; set; }
        public string c_Caja { get; set; }
        public System.DateTime f_Fecha { get; set; }
        public string Codigo { get; set; }
        public double Cantidad { get; set; }
        public double Precio { get; set; }
        public double Subtotal { get; set; }
        public double Impuesto { get; set; }
        public double Total { get; set; }
        public double Descuento { get; set; }
        public double Impuesto1 { get; set; }
        public double Impuesto2 { get; set; }
        public double Impuesto3 { get; set; }
        public int Estatus { get; set; }
        public double n_Costo { get; set; }
        public string c_Localidad { get; set; }
        public string Cod_Principal { get; set; }
        public double n_Devueltos { get; set; }
        public double n_PrecioReal { get; set; }
        public Nullable<System.DateTime> h_Hora { get; set; }
        public Nullable<int> n_Linea { get; set; }
        public string c_Concepto { get; set; }
        public string c_Usuario { get; set; }
        public double Turno { get; set; }
        public decimal ID { get; set; }
        public string cu_Texto { get; set; }
    }
}
