//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_VENTAS_RETENCIONES
    {
        public string CS_DOCUMENTO { get; set; }
        public string CS_CONCEPTO { get; set; }
        public double NS_MONTOBASE { get; set; }
        public double NS_PORCENTAJE { get; set; }
        public double NS_MONTO { get; set; }
        public System.DateTime FS_FECHA_HORA { get; set; }
    }
}
