//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_VENTAS
    {
        public string cs_ORGANIZACION { get; set; }
        public string c_DOCUMENTO { get; set; }
        public string c_CONCEPTO { get; set; }
        public System.DateTime d_FECHA { get; set; }
        public string c_DESCRIPCION { get; set; }
        public string c_direccion { get; set; }
        public string c_rif { get; set; }
        public string c_nit { get; set; }
        public string c_telefono { get; set; }
        public string c_status { get; set; }
        public string c_CODCLIENTE { get; set; }
        public string c_CODLOCALIDAD { get; set; }
        public string c_CODMONEDA { get; set; }
        public double n_FACTORCAMBIO { get; set; }
        public double n_DESCUENTO { get; set; }
        public string c_OBSERVACION { get; set; }
        public string c_RELACION { get; set; }
        public string c_CODVENDEDOR { get; set; }
        public System.DateTime d_fecha_recepcion { get; set; }
        public double NS_BASE_RETENCION { get; set; }
        public double NS_RETENCION { get; set; }
        public double N_SUBTOTAL { get; set; }
        public double N_IMPUESTO { get; set; }
        public double NU_MONTO_SERVICIO { get; set; }
        public double N_TOTAL { get; set; }
        public double NU_MONTO_CANCELADO { get; set; }
        public string C_CODDEPOSITO { get; set; }
        public double n_baseimp { get; set; }
        public decimal id { get; set; }
        public string c_orden_compra { get; set; }
        public decimal codconcepto { get; set; }
        public string cu_vendedor_cod { get; set; }
        public string cu_codafiliado { get; set; }
        public double N_VUELTO { get; set; }
        public double NU_MONTO_VUELTO { get; set; }
        public string cs_comprobanteContable { get; set; }
        public string cs_codlocalidad { get; set; }
        public string CS_NUMERO_TRANSFERENCIA { get; set; }
        public string CS_CODUNIDAD { get; set; }
    }
}
