//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_VENDEDORES
    {
        public string CU_VENDEDOR_COD { get; set; }
        public string CU_VENDEDOR_DES { get; set; }
        public bool BU_ACTIVO { get; set; }
        public string cs_RELACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_LOGIN { get; set; }
        public string cs_PASSWORD { get; set; }
        public System.DateTime cs_INGRESO { get; set; }
        public System.DateTime cs_MODIFICADO { get; set; }
        public string cs_GRUPO_COMISION { get; set; }
        public bool bu_cualquier_cuenta { get; set; }
        public string cu_rif { get; set; }
        public string c_grupo { get; set; }
        public string cs_tipo { get; set; }
        public string C_COMISIONES { get; set; }
    }
}
