//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_VENTAS_IMPUESTOS
    {
        public string cs_documento { get; set; }
        public string cs_TIPODOC { get; set; }
        public double ns_BaseImpuesto { get; set; }
        public double ns_MontoImpuesto { get; set; }
        public double ns_PorcentajeImpuesto { get; set; }
        public string cs_codProveedor { get; set; }
        public string cs_codlocalidad { get; set; }
    }
}
