//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_VENDEDORES_GRUPOS_COMISION
    {
        public string cs_GRUPO_COMISION { get; set; }
        public string cs_DESCRIPCION_GRUPO { get; set; }
        public double cs_PORCENTAJE { get; set; }
        public int cs_ITEM_AFECTADO { get; set; }
        public bool cs_CONSIDERAR_PARA_IMPUESTO { get; set; }
    }
}
