//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_VENTAS_POS_IMPUESTOS
    {
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_DOCUMENTO { get; set; }
        public string cs_TIPO_DOCUMENTO { get; set; }
        public string cs_CAJA { get; set; }
        public double nu_TURNO { get; set; }
        public double ns_MONTO_BASEIMPUESTO { get; set; }
        public double ns_IMPUESTO { get; set; }
        public double ns_MONTO_IMPUESTO { get; set; }
        public decimal ID { get; set; }
    }
}
