//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_VENTAS_POS
    {
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_DOCUMENTO { get; set; }
        public string cs_CODIGOSERVICIO { get; set; }
        public string cs_TIPO_DOCUMENTO { get; set; }
        public string cs_CAJA { get; set; }
        public double nu_TURNO { get; set; }
        public string cs_USUARIO { get; set; }
        public string cs_CODIGO_VENDEDOR { get; set; }
        public System.DateTime ds_FECHA { get; set; }
        public string cu_CLIENTE { get; set; }
        public string cu_NOMBRE_CLIENTE { get; set; }
        public string cu_RIFCLIENTE { get; set; }
        public string cu_DIRECCION_CLIENTE { get; set; }
        public string cu_TELEFONO_CLIENTE { get; set; }
        public string cs_MONEDA_PREFERENCIAL { get; set; }
        public double ns_FACTOR_PREFERENCIAL { get; set; }
        public int nu_PRODUCTOS { get; set; }
        public double nu_MONTO_SUBTOTAL { get; set; }
        public double nu_MONTO_IMPUESTO { get; set; }
        public double nu_MONTO_DESCUENTO { get; set; }
        public double nu_MONTO_SERVICIO { get; set; }
        public double nu_MONTO_TOTAL { get; set; }
        public double nu_MONTO_CANCELADO { get; set; }
        public double nu_MONTO_VUELTO { get; set; }
        public string cu_direccion_despacho { get; set; }
        public string cs_documento_rel { get; set; }
        public bool bu_impresa { get; set; }
    }
}
