//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuarioDev
    {
        public string CodigoUser { get; set; }
        public string Caja { get; set; }
        public string Usuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string documento { get; set; }
        public string cliente { get; set; }
        public double monto { get; set; }
        public string FacturaRelacion { get; set; }
        public string Cajera { get; set; }
        public decimal id { get; set; }
    }
}
