//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_DETALLEPAGO
    {
        public string c_Factura { get; set; }
        public string c_CodMoneda { get; set; }
        public string c_CodDenominacion { get; set; }
        public double n_Factor { get; set; }
        public string c_CodBanco { get; set; }
        public string c_Banco { get; set; }
        public string c_Numero { get; set; }
        public double n_Cantidad { get; set; }
        public double n_Monto { get; set; }
        public System.DateTime d_FechaHora { get; set; }
        public bool b_PermiteAvance { get; set; }
        public double n_MontoAvance { get; set; }
        public decimal ID { get; set; }
    }
}
