//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_BOTONES
    {
        public string C_CAJA { get; set; }
        public int N_BOTON { get; set; }
        public int N_SUBBOTON { get; set; }
        public string C_CODIGO { get; set; }
    }
}
