//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CAJA
    {
        public string cs_CAJA { get; set; }
        public string C_Codigo { get; set; }
        public string C_Cajero { get; set; }
        public string C_Desc_Cajero { get; set; }
        public int N_Cortes { get; set; }
        public double N_Vendido { get; set; }
        public int N_Compras { get; set; }
        public string c_estado { get; set; }
        public System.DateTime h_inicio { get; set; }
        public Nullable<System.DateTime> h_final { get; set; }
        public double n_suspendido { get; set; }
        public int Turno { get; set; }
        public System.DateTime d_fecha_inicio { get; set; }
        public Nullable<System.DateTime> d_fecha_cierre { get; set; }
        public bool B_INVENTARIO { get; set; }
        public double N_MONTOREINTEGRO_TOT { get; set; }
        public int N_REINTEGRO_TOT { get; set; }
        public decimal ID { get; set; }
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public decimal ns_TURNO { get; set; }
        public string cs_ESTADO { get; set; }
        public System.DateTime ds_FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> ds_FECHA_CIERRE { get; set; }
        public string cs_CAJERO { get; set; }
        public string cs_NOMBRE_CAJERO { get; set; }
        public int ns_NUMERO_OPERACIONES { get; set; }
        public double ns_MONTO_VENDIDO { get; set; }
        public int ns_NUMERO_DEVOLUCIONES { get; set; }
        public double ns_MONTO_DEVUELTO { get; set; }
        public int nu_REINTEGROS_TOTALES { get; set; }
        public double nu_MONTOREINTEGRO_TOTAL { get; set; }
        public double nu_monto_retiros { get; set; }
        public int ns_CORTES { get; set; }
        public double ns_SUSPENDIDO { get; set; }
        public bool bs_INVENTARIO { get; set; }
        public double nu_montofondo { get; set; }
    }
}
