//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CIERRES
    {
        public string c_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> d_FECHA { get; set; }
        public string c_CODLOCALIDAD { get; set; }
        public string c_CODMONEDA { get; set; }
        public string c_CODDENOMINA { get; set; }
        public string c_CODBANCO { get; set; }
        public Nullable<double> n_FACTOR { get; set; }
        public Nullable<int> n_CANTIDAD { get; set; }
        public Nullable<double> n_BOLIVARES { get; set; }
        public string c_TDC { get; set; }
        public int c_cerrado { get; set; }
        public string C_Concepto { get; set; }
        public string C_Real { get; set; }
        public string C_Codcajero { get; set; }
        public string C_Factura { get; set; }
        public int n_depositado { get; set; }
        public Nullable<int> n_falta { get; set; }
        public Nullable<double> n_valor { get; set; }
        public string c_num_cierre { get; set; }
        public Nullable<double> TURNO { get; set; }
        public decimal ID { get; set; }
        public string CS_TMPUSUARIO { get; set; }
    }
}
