//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CONSUMO_TEMP
    {
        public string cs_CodigoServicio { get; set; }
        public string cs_Comanda { get; set; }
        public string c_Parte { get; set; }
        public double n_Cantidad { get; set; }
        public string cs_Relacion { get; set; }
        public double ns_Linea { get; set; }
        public string cs_Descripcion_Producto { get; set; }
        public string cu_Texto { get; set; }
        public string InfoComandaXPersona { get; set; }
        public int CodigoPlato { get; set; }
        public int CodigoGrupo { get; set; }
        public int GrupoSistema { get; set; }
        public int OrdenPlato { get; set; }
    }
}
