//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CAJA_BOTONES_DIGITALES_PERFIL_TEMP
    {
        public string CodigoPerfil { get; set; }
        public string Relacion { get; set; }
        public string Clave { get; set; }
        public string texto { get; set; }
        public string imagen { get; set; }
        public string tag { get; set; }
        public Nullable<int> Posicion { get; set; }
        public string Mascara { get; set; }
        public string Tecla { get; set; }
        public decimal id { get; set; }
    }
}
