//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CONSUMO
    {
        public string cs_CAJA { get; set; }
        public string cs_COMANDA { get; set; }
        public string cs_CODIGOCUENTA { get; set; }
        public string cs_CODIGOSERVICIO { get; set; }
        public string cs_RELACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_ORGANIZACION { get; set; }
        public decimal ns_LINEA { get; set; }
        public string cs_CODIGO_PRODUCTO_PADRE { get; set; }
        public string cu_CODIGO_PRODUCTO { get; set; }
        public string cs_CODIGO_PRINCIPAL { get; set; }
        public string cu_IMPRESORA { get; set; }
        public string cs_DESCRIPCION_PRODUCTO { get; set; }
        public string cu_texto { get; set; }
        public int nu_tiposervicio { get; set; }
        public double nu_CANTIDAD { get; set; }
        public double ns_COSTO { get; set; }
        public Nullable<double> ns_PRECIO { get; set; }
        public double ns_PRECIO_REAL { get; set; }
        public double ns_SUBTOTAL { get; set; }
        public double ns_IMPUESTO { get; set; }
        public double ns_MONTO_BASEIMPUESTO { get; set; }
        public double ns_TOTAL { get; set; }
        public double nu_DESCUENTO { get; set; }
        public double ns_FACTOR { get; set; }
        public string cs_MONEDA { get; set; }
        public string cs_CONCEPTO { get; set; }
        public string cs_deposito { get; set; }
        public System.DateTime FS_FECHA_HORA { get; set; }
        public bool KDS { get; set; }
        public string cu_KDS { get; set; }
        public int EstatusKDS { get; set; }
        public int IndiceCPP { get; set; }
        public string InfoComandaXPersona { get; set; }
        public int CodigoPlato { get; set; }
        public int CodigoGrupo { get; set; }
        public int GrupoSistema { get; set; }
        public int OrdenPlato { get; set; }
        public double nu_Cant_Reintegro { get; set; }
    }
}
