//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CONSUMO_IMPUESTOS
    {
        public string cs_CODIGOSERVICIO { get; set; }
        public string cs_COMANDA { get; set; }
        public string cs_CODIGOCUENTA { get; set; }
        public string cs_CODIGOPRODUCTO { get; set; }
        public string cs_RELACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_ORGANIZACION { get; set; }
        public int ns_LINEA { get; set; }
        public double ns_IMPUESTO { get; set; }
        public double ns_MONTO_BASEIMPUESTO { get; set; }
        public double ns_MONTO_IMPUESTO { get; set; }
        public decimal ID { get; set; }
        public decimal IDOrdenPlato { get; set; }
    }
}
