//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CIERRE_POS
    {
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_DOCUMENTO { get; set; }
        public string cs_NUMERO_DOCUMENTO { get; set; }
        public string cs_CAJA { get; set; }
        public decimal cs_TURNO { get; set; }
        public string cs_MONEDA { get; set; }
        public string cs_DENOMINACION { get; set; }
        public double ns_FACTORMONEDA { get; set; }
        public double ns_CANTIDAD_ORIGINAL { get; set; }
        public double ns_CANTIDAD_ACTUAL { get; set; }
        public double ns_VALOR_DENOMINACION { get; set; }
        public string cs_ENTIDAD_EMISORA { get; set; }
        public string cs_NUMERO { get; set; }
        public double ns_MONTO_ORIGINAL { get; set; }
        public double ns_MONTO_ACTUAL { get; set; }
        public string cs_TIPO_MOVIMIENTO { get; set; }
        public bool bs_CONSOLIDADA { get; set; }
        public decimal ID { get; set; }
    }
}
