//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_DEVOLUCION
    {
        public string C_Numero { get; set; }
        public string C_Caja { get; set; }
        public Nullable<System.DateTime> F_Fecha { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Impuesto1 { get; set; }
        public Nullable<double> Impuesto2 { get; set; }
        public Nullable<double> Impuesto3 { get; set; }
        public string c_dpto { get; set; }
        public string c_grupo { get; set; }
        public string c_subgrupo { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<double> n_costo { get; set; }
        public string c_localidad { get; set; }
        public string COD_PRINCIPAL { get; set; }
        public Nullable<double> n_devueltos { get; set; }
        public Nullable<double> n_reintegros { get; set; }
        public Nullable<double> n_precioreal { get; set; }
        public decimal id { get; set; }
    }
}
