//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_DEPOSITOS
    {
        public string C_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> D_FECHA { get; set; }
        public string C_CODLOCALIDAD { get; set; }
        public string C_CODMONEDA { get; set; }
        public string C_CODDENOMINACION { get; set; }
        public Nullable<double> N_FACTOR { get; set; }
        public Nullable<double> N_CANTIDAD { get; set; }
        public Nullable<double> N_VALOR { get; set; }
        public Nullable<double> N_BOLIVARES { get; set; }
        public string C_CODBANCO { get; set; }
        public string C_NUMERO { get; set; }
        public string C_REAL { get; set; }
        public string c_num_cierre { get; set; }
    }
}
