//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_DENOMINA_SERIALES_TEMP
    {
        public string cs_CAJA { get; set; }
        public string cs_MONEDA { get; set; }
        public string cs_DENOMINACION { get; set; }
        public string cu_SERIAL { get; set; }
        public decimal ID { get; set; }
    }
}
