//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_DENOMINA_TEMP
    {
        public string CODMONEDA { get; set; }
        public string CODDENOMINA { get; set; }
        public string DESDENOmINA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<double> VALOR { get; set; }
        public Nullable<double> FACTOR { get; set; }
        public string CAJA { get; set; }
        public decimal id { get; set; }
        public string codigobanco { get; set; }
        public string USUARIO { get; set; }
    }
}
