//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_OPERACIONES_AUTORIZADAS
    {
        public decimal id { get; set; }
        public System.DateTime fecha { get; set; }
        public string caja { get; set; }
        public string codigoCajero { get; set; }
        public int turno { get; set; }
        public string codigoUsuarioAutorizante { get; set; }
        public string operacionRealizada { get; set; }
        public string codigoCliente { get; set; }
        public string idCliente { get; set; }
        public string nombreCliente { get; set; }
        public string tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
    }
}
