//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_PRODUCTOSPARTES
    {
        public string cu_CodigoProductoPrincipal { get; set; }
        public string cu_CodigoProductoParte { get; set; }
        public double nu_Cantidad { get; set; }
        public decimal ID { get; set; }
        public int bu_Variable { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public string N_CAJA { get; set; }
    }
}
