//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_MONEDAS
    {
        public string C_CODMONEDA { get; set; }
        public string C_DESCRIPCION { get; set; }
        public double N_FACTOR { get; set; }
        public bool B_PREFERENCIA { get; set; }
        public string C_OBSERVACIO { get; set; }
        public bool B_ACTIVA { get; set; }
        public string C_SIMBOLO { get; set; }
        public int N_DECIMALES { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public string N_CAJA { get; set; }
        public decimal ID { get; set; }
        public bool bUsoEnPOS { get; set; }
    }
}
