//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_ETIQUETAS
    {
        public string c_codigo { get; set; }
        public string c_descripcio { get; set; }
        public string c_longitud { get; set; }
        public double n_longitud { get; set; }
        public int n_pos_ini_1 { get; set; }
        public int n_caracteres_1 { get; set; }
        public int c_campo { get; set; }
        public int n_pos_ini_2 { get; set; }
        public int n_caracteres_2 { get; set; }
        public bool b_maneja_decimal { get; set; }
        public int n_pos_ini_3 { get; set; }
        public int n_caracteres_3 { get; set; }
        public bool b_activa { get; set; }
        public string n_caja { get; set; }
        public int tipocambio { get; set; }
        public decimal id { get; set; }
        public bool B_VERIFICADIGITO { get; set; }
    }
}
