//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_PRODUCTOS
    {
        public string c_Codigo { get; set; }
        public string c_Descri { get; set; }
        public string c_Departamento { get; set; }
        public string c_Grupo { get; set; }
        public string c_Subgrupo { get; set; }
        public string c_Marca { get; set; }
        public string c_Modelo { get; set; }
        public bool c_Procede { get; set; }
        public double n_CostoAct { get; set; }
        public double n_CostoAnt { get; set; }
        public double n_CostoPro { get; set; }
        public double n_CostoRep { get; set; }
        public double n_Precio1 { get; set; }
        public double n_Precio2 { get; set; }
        public double n_Precio3 { get; set; }
        public int c_Seriales { get; set; }
        public int c_Compuesto { get; set; }
        public string c_Presenta { get; set; }
        public double n_Peso { get; set; }
        public double n_Volumen { get; set; }
        public double n_CantiBul { get; set; }
        public double n_PesoBul { get; set; }
        public double n_VolBul { get; set; }
        public byte[] c_FileImagen { get; set; }
        public double n_Impuesto1 { get; set; }
        public double n_Impuesto2 { get; set; }
        public double n_Impuesto3 { get; set; }
        public string c_Cod_Arancel { get; set; }
        public string c_Des_Arancel { get; set; }
        public double n_Por_Arancel { get; set; }
        public double n_Costo_Original { get; set; }
        public string c_Observacio { get; set; }
        public int n_Activo { get; set; }
        public int n_TipoPeso { get; set; }
        public double n_PrecioO { get; set; }
        public System.DateTime f_Inicial { get; set; }
        public System.DateTime f_Final { get; set; }
        public System.DateTime h_Inicial { get; set; }
        public System.DateTime h_Final { get; set; }
        public System.DateTime Add_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
        public string c_CodFabricante { get; set; }
        public int Hablador { get; set; }
        public string c_CodMoneda { get; set; }
        public int Cant_Decimales { get; set; }
        public double Moneda_Ant { get; set; }
        public double Moneda_Act { get; set; }
        public double Moneda_Pro { get; set; }
        public decimal ID { get; set; }
        public string c_UsuarioAdd { get; set; }
        public string c_UsuarioUpd { get; set; }
        public string c_Codigo_Base { get; set; }
        public string c_Descri_Base { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Text6 { get; set; }
        public string Text7 { get; set; }
        public string Text8 { get; set; }
        public System.DateTime Date1 { get; set; }
        public double Nume1 { get; set; }
        public string n_Cantidad_Tmp { get; set; }
        public string c_Cod_Plantilla { get; set; }
        public string n_Prod_Ext { get; set; }
        public string n_Pro_Ext { get; set; }
        public int nu_Tipo_Producto { get; set; }
        public string n_Caja { get; set; }
        public int TipoCambio { get; set; }
        public int nu_InsumoInterno { get; set; }
        public int nu_PrecioRegulado { get; set; }
        public double nu_PocentajeMerma { get; set; }
        public int nu_NivelClave { get; set; }
        public string cu_Descripcion_Corta { get; set; }
        public bool bs_PermiteTeclado { get; set; }
        public bool bs_PermiteCantidad { get; set; }
        public double nu_StockMin { get; set; }
        public double nu_StockMax { get; set; }
    }
}
