//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_VENTAS_VOLUMEN
    {
        public string c_codigo { get; set; }
        public float desde { get; set; }
        public float hasta { get; set; }
        public double n_precio1 { get; set; }
        public double n_precio2 { get; set; }
        public double n_precio3 { get; set; }
        public decimal N_VOLUMEN { get; set; }
        public string N_CAJA { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public decimal ID { get; set; }
    }
}
