//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_BANCOS
    {
        public string C_CODIGO { get; set; }
        public string C_DESCRIPCIO { get; set; }
        public string C_GRUPO { get; set; }
        public string C_OBSERVACIO { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public string N_CAJA { get; set; }
        public decimal ID { get; set; }
        public double N_IDB { get; set; }
        public bool bs_verificacionoperaciones_especiales { get; set; }
        public string cs_mensaje { get; set; }
        public string ns_codigooperacion { get; set; }
        public string cs_rtfcheque { get; set; }
        public string cs_codigobanco_che { get; set; }
        public bool bActivo { get; set; }
        public bool bUsoEnPOS { get; set; }
    }
}
