//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_CLIENTES
    {
        public string c_CODCLIENTE { get; set; }
        public string c_DESCRIPCIO { get; set; }
        public string c_GRUPO { get; set; }
        public string c_RIF { get; set; }
        public string C_NIT { get; set; }
        public string c_REPRESENTA { get; set; }
        public string c_CARGO { get; set; }
        public string c_DIRECCION { get; set; }
        public string c_CIUDAD { get; set; }
        public string c_ESTADO { get; set; }
        public string c_PAIS { get; set; }
        public string c_EMAIL { get; set; }
        public string c_TELEFONO { get; set; }
        public string c_FAX { get; set; }
        public string c_WEB { get; set; }
        public double n_LIMITE { get; set; }
        public short n_DIAS { get; set; }
        public short n_PRECIO { get; set; }
        public double n_DESCUENTO { get; set; }
        public string c_OBSERVACIO { get; set; }
        public string c_impuesto { get; set; }
        public bool n_activo { get; set; }
        public System.DateTime update_date { get; set; }
        public System.DateTime add_date { get; set; }
        public System.DateTime f_cumpleanos { get; set; }
        public int ESTATUS { get; set; }
        public string N_CAJA { get; set; }
        public decimal ID { get; set; }
        public int N_TIPO1 { get; set; }
        public string C_CODCLIENTE_REL1 { get; set; }
        public decimal N_RETENCION1 { get; set; }
        public int Nu_tipodescuento { get; set; }
        public int N_DiasIntMora { get; set; }
        public double N_InteresesMora { get; set; }
        public byte[] c_fileimagen { get; set; }
        public int N_TIPO { get; set; }
        public string C_CODCLIENTE_REL { get; set; }
        public decimal N_RETENCION { get; set; }
        public Nullable<double> NU_PUNTOSACUMULADOS { get; set; }
        public Nullable<bool> RESTRINGIDO { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public string CS_COMPRADOR { get; set; }
        public string CS_CODFRECUENTE { get; set; }
        public bool BS_CONTRIBUYENTE { get; set; }
    }
}
