//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_USUARIOS
    {
        public string CODUSUARIO { get; set; }
        public string PASSWORD { get; set; }
        public string LOGIN_NAME { get; set; }
        public string DESCRIPCION { get; set; }
        public string CLAVE { get; set; }
        public string LOCALIDAD { get; set; }
        public decimal NIVEL { get; set; }
        public decimal VENDEDOR { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public bool TIPO_USUARIO { get; set; }
        public bool MOD_PRECIO_VENTA { get; set; }
        public bool MOD_COSTO_COMPRA { get; set; }
        public string N_CAJA { get; set; }
        public int TIPO_CAMBIO { get; set; }
        public int ID { get; set; }
        public int BU_CAMBIA_CLAVE { get; set; }
    }
}
