//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PENDIENTE_CODIGO
    {
        public string c_Codigo { get; set; }
        public string c_CodNasa { get; set; }
        public string c_Descripcion { get; set; }
        public int n_Cantidad { get; set; }
        public int nu_Intercambio { get; set; }
        public int TipoCambio { get; set; }
        public int nu_TipoPrecio { get; set; }
        public decimal ID { get; set; }
    }
}
