//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PEND_PRODXPROV
    {
        public string c_codigo { get; set; }
        public string c_codprovee { get; set; }
        public string c_numero_compra { get; set; }
        public System.DateTime d_fecha { get; set; }
        public double n_costo { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
        public System.DateTime ADD_DATE { get; set; }
        public int ESTATUS { get; set; }
        public int B_PREFERENCIAL { get; set; }
        public decimal ID { get; set; }
        public string N_PROD_EXT { get; set; }
        public string n_Caja { get; set; }
    }
}
