//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_REPORTES
    {
        public string cs_CODIGO_REPORTE { get; set; }
        public string cs_BASE_DATOS { get; set; }
        public string cs_TABLA { get; set; }
        public string cs_DESCRIPCION { get; set; }
        public string cs_CAMPO { get; set; }
        public string cs_NOMBRE_VARIABLE { get; set; }
        public int cs_TIPOCAMPO { get; set; }
        public decimal ID { get; set; }
    }
}
