//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_SITIO_RESERVAR
    {
        public string cu_CODIGO_MESA { get; set; }
        public string cu_NombreCliente { get; set; }
        public string cu_RELACION { get; set; }
        public System.DateTime cu_FECHA_RESERVACION { get; set; }
        public System.DateTime cu_HORA_RESERVACION { get; set; }
        public System.DateTime cu_TIEMPO_ANTICIPACION { get; set; }
        public System.DateTime cu_TIEMPO_ESPERA { get; set; }
        public decimal ID { get; set; }
        public int nu_Estado { get; set; }
    }
}
