//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_SORTEOS
    {
        public string CS_CODIGO_SORTEO { get; set; }
        public string CS_CODARTICULO { get; set; }
        public double NU_MINCANTIDAD { get; set; }
        public double NU_PUNTOS { get; set; }
        public int NU_TIPOSORTEO { get; set; }
    }
}
