//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_VENTAS_POS_PAGOS
    {
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_DOCUMENTO { get; set; }
        public string cs_TIPO_DOCUMENTO { get; set; }
        public string cs_CAJA { get; set; }
        public double ns_TURNO { get; set; }
        public string cs_CAJERO { get; set; }
        public System.DateTime ds_FECHA { get; set; }
        public string cu_MONEDA { get; set; }
        public string cu_DENOMINACION { get; set; }
        public string cs_UTIL { get; set; }
        public string cu_CODIGO_BANCO { get; set; }
        public string cu_NOMBRE_BANCO { get; set; }
        public string cu_NUMERO { get; set; }
        public double ns_FACTOR { get; set; }
        public double nu_MONTO { get; set; }
        public double nu_FALTA { get; set; }
        public string cu_OPERADOR { get; set; }
        public string cu_CLAVE { get; set; }
        public decimal ID { get; set; }
        public double nu_Tip { get; set; }
    }
}
