//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_VENTAS_POS
    {
        public string cs_ORGANIZACION { get; set; }
        public string cs_LOCALIDAD { get; set; }
        public string cs_DOCUMENTO { get; set; }
        public string cs_CAJA { get; set; }
        public double ns_TURNO { get; set; }
        public string cs_USUARIO { get; set; }
        public System.DateTime ds_FECHA { get; set; }
        public int ns_LINEA { get; set; }
        public string cs_CODIGO_PRODUCTO_PADRE { get; set; }
        public string cu_CODIGO_PRODUCTO { get; set; }
        public string cs_CODIGO_PRINCIPAL { get; set; }
        public string cs_DESCRIPCION_PRODUCTO { get; set; }
        public string cs_COMANDA { get; set; }
        public string cs_TIPO_DOCUMENTO { get; set; }
        public int ns_ESTATUS { get; set; }
        public double nu_CANTIDAD { get; set; }
        public double ns_COSTO { get; set; }
        public double ns_PRECIO { get; set; }
        public double ns_PRECIO_REAL { get; set; }
        public double ns_SUBTOTAL { get; set; }
        public double ns_IMPUESTO { get; set; }
        public double ns_MONTO_BASEIMPUESTO { get; set; }
        public double ns_TOTAL { get; set; }
        public double ns_DESCUENTO { get; set; }
        public double ns_DEVUELTOS { get; set; }
        public double ns_FACTOR { get; set; }
        public string cs_MONEDA { get; set; }
        public decimal ID { get; set; }
        public string cs_deposito { get; set; }
        public string cu_impresora { get; set; }
        public int CodigoPlato { get; set; }
        public string cu_Texto { get; set; }
    }
}
