//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paladar20_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VAD20Entities : DbContext
    {
        public VAD20Entities()
            : base("name=VAD20Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C0NE_TIME_SCRIPT_EVENTS> C0NE_TIME_SCRIPT_EVENTS { get; set; }
        public virtual DbSet<MA_AVANCE_EFECTIVO> MA_AVANCE_EFECTIVO { get; set; }
        public virtual DbSet<MA_AVANCE_EFECTIVO_DETPAG> MA_AVANCE_EFECTIVO_DETPAG { get; set; }
        public virtual DbSet<MA_BLACKSTONE_PREPAID_ORDERS> MA_BLACKSTONE_PREPAID_ORDERS { get; set; }
        public virtual DbSet<MA_BLACKSTONE_PREPAID_SERVICE_TYPE> MA_BLACKSTONE_PREPAID_SERVICE_TYPE { get; set; }
        public virtual DbSet<MA_BLACKSTONE_PREPAID_STATUS> MA_BLACKSTONE_PREPAID_STATUS { get; set; }
        public virtual DbSet<MA_BOTONES> MA_BOTONES { get; set; }
        public virtual DbSet<MA_BOTONES_CAJA> MA_BOTONES_CAJA { get; set; }
        public virtual DbSet<MA_BOTONES_PERFILES> MA_BOTONES_PERFILES { get; set; }
        public virtual DbSet<MA_BOTONES_TMP> MA_BOTONES_TMP { get; set; }
        public virtual DbSet<MA_CAJA> MA_CAJA { get; set; }
        public virtual DbSet<MA_CAJA_BOTONES> MA_CAJA_BOTONES { get; set; }
        public virtual DbSet<MA_CAJA_BOTONES_DIGITALES> MA_CAJA_BOTONES_DIGITALES { get; set; }
        public virtual DbSet<MA_CAJA_BOTONES_DIGITALES_PERFIL> MA_CAJA_BOTONES_DIGITALES_PERFIL { get; set; }
        public virtual DbSet<MA_CAJA_CONFIGURACION> MA_CAJA_CONFIGURACION { get; set; }
        public virtual DbSet<MA_CAJA_PARAMETROS> MA_CAJA_PARAMETROS { get; set; }
        public virtual DbSet<MA_CAMBIOS> MA_CAMBIOS { get; set; }
        public virtual DbSet<MA_CIERRE_POS_TOTAL> MA_CIERRE_POS_TOTAL { get; set; }
        public virtual DbSet<MA_CIERRES> MA_CIERRES { get; set; }
        public virtual DbSet<MA_CIERRES_POS_PARCIAL> MA_CIERRES_POS_PARCIAL { get; set; }
        public virtual DbSet<MA_CIERRExFACTURA> MA_CIERRExFACTURA { get; set; }
        public virtual DbSet<MA_CODIGOS> MA_CODIGOS { get; set; }
        public virtual DbSet<MA_CONSUMO> MA_CONSUMO { get; set; }
        public virtual DbSet<MA_CONSUMO_IMPUESTOS> MA_CONSUMO_IMPUESTOS { get; set; }
        public virtual DbSet<MA_CONSUMO_TIPOS> MA_CONSUMO_TIPOS { get; set; }
        public virtual DbSet<MA_CORRELATIVOS> MA_CORRELATIVOS { get; set; }
        public virtual DbSet<MA_DEPOSITOS> MA_DEPOSITOS { get; set; }
        public virtual DbSet<MA_DETALLEPAGO> MA_DETALLEPAGO { get; set; }
        public virtual DbSet<MA_DEVOLUCION> MA_DEVOLUCION { get; set; }
        public virtual DbSet<MA_DISPOSITIVOS> MA_DISPOSITIVOS { get; set; }
        public virtual DbSet<MA_DISPOSITIVOS_CAJA> MA_DISPOSITIVOS_CAJA { get; set; }
        public virtual DbSet<MA_DOCUMENTOS_FISCAL> MA_DOCUMENTOS_FISCAL { get; set; }
        public virtual DbSet<MA_ERRORES> MA_ERRORES { get; set; }
        public virtual DbSet<MA_ESTRUC_CAJA> MA_ESTRUC_CAJA { get; set; }
        public virtual DbSet<MA_ETIQUETAS> MA_ETIQUETAS { get; set; }
        public virtual DbSet<MA_IMPRESORAS> MA_IMPRESORAS { get; set; }
        public virtual DbSet<MA_KDS> MA_KDS { get; set; }
        public virtual DbSet<MA_MENSAJES> MA_MENSAJES { get; set; }
        public virtual DbSet<MA_OPERACIONES_AUTORIZADAS> MA_OPERACIONES_AUTORIZADAS { get; set; }
        public virtual DbSet<MA_PAGOS> MA_PAGOS { get; set; }
        public virtual DbSet<MA_PAGOS_IMPUESTOS> MA_PAGOS_IMPUESTOS { get; set; }
        public virtual DbSet<MA_PERFILES_TEMP> MA_PERFILES_TEMP { get; set; }
        public virtual DbSet<MA_PLATOS> MA_PLATOS { get; set; }
        public virtual DbSet<MA_PLATOS_GRUPOS> MA_PLATOS_GRUPOS { get; set; }
        public virtual DbSet<MA_PLATOS_GRUPOS_PRO> MA_PLATOS_GRUPOS_PRO { get; set; }
        public virtual DbSet<MA_PRODUCTOS> MA_PRODUCTOS { get; set; }
        public virtual DbSet<MA_REPORTES> MA_REPORTES { get; set; }
        public virtual DbSet<MA_RET_CIE_CP> MA_RET_CIE_CP { get; set; }
        public virtual DbSet<MA_SITIO> MA_SITIO { get; set; }
        public virtual DbSet<MA_SORTEOS> MA_SORTEOS { get; set; }
        public virtual DbSet<MA_TABLAS_SYNCRONIZAR> MA_TABLAS_SYNCRONIZAR { get; set; }
        public virtual DbSet<MA_TRANSACCION> MA_TRANSACCION { get; set; }
        public virtual DbSet<MA_VENDEDORES> MA_VENDEDORES { get; set; }
        public virtual DbSet<MA_VENTAS_POS> MA_VENTAS_POS { get; set; }
        public virtual DbSet<MA_VENTAS_POS_IMPUESTOS> MA_VENTAS_POS_IMPUESTOS { get; set; }
        public virtual DbSet<MA_VENTAS_VOLUMEN> MA_VENTAS_VOLUMEN { get; set; }
        public virtual DbSet<MA_VENTAS_VOLUMENTOTAL> MA_VENTAS_VOLUMENTOTAL { get; set; }
        public virtual DbSet<TMP_DETALLEPAGO> TMP_DETALLEPAGO { get; set; }
        public virtual DbSet<TMP_SORTEOS> TMP_SORTEOS { get; set; }
        public virtual DbSet<TR_BOTONES> TR_BOTONES { get; set; }
        public virtual DbSet<TR_BOTONES_TMP> TR_BOTONES_TMP { get; set; }
        public virtual DbSet<TR_BOTONES_TMP1> TR_BOTONES_TMP1 { get; set; }
        public virtual DbSet<TR_CAJA> TR_CAJA { get; set; }
        public virtual DbSet<TR_CAJA_BOTONES_DIGITALES> TR_CAJA_BOTONES_DIGITALES { get; set; }
        public virtual DbSet<TR_CAJA_BOTONES_DIGITALES_PERFIL> TR_CAJA_BOTONES_DIGITALES_PERFIL { get; set; }
        public virtual DbSet<TR_CAJA_BOTONES_DIGITALES_PERFIL_TEMP> TR_CAJA_BOTONES_DIGITALES_PERFIL_TEMP { get; set; }
        public virtual DbSet<TR_CIERRE_POS_SERIALES> TR_CIERRE_POS_SERIALES { get; set; }
        public virtual DbSet<TR_CIERRES> TR_CIERRES { get; set; }
        public virtual DbSet<TR_CONSUMO> TR_CONSUMO { get; set; }
        public virtual DbSet<TR_CONSUMO_IMPUESTOS> TR_CONSUMO_IMPUESTOS { get; set; }
        public virtual DbSet<TR_DEPOSITOS> TR_DEPOSITOS { get; set; }
        public virtual DbSet<TR_OPERACIONES_AUTORIZADAS> TR_OPERACIONES_AUTORIZADAS { get; set; }
        public virtual DbSet<TR_PEND_CODIGOS> TR_PEND_CODIGOS { get; set; }
        public virtual DbSet<TR_PEND_DENOMINACION> TR_PEND_DENOMINACION { get; set; }
        public virtual DbSet<TR_PEND_ETIQUETAS> TR_PEND_ETIQUETAS { get; set; }
        public virtual DbSet<TR_PEND_MONEDAS> TR_PEND_MONEDAS { get; set; }
        public virtual DbSet<TR_PEND_PRODUCTOSPARTES> TR_PEND_PRODUCTOSPARTES { get; set; }
        public virtual DbSet<TR_PEND_PRODXPROV> TR_PEND_PRODXPROV { get; set; }
        public virtual DbSet<TR_PEND_USUARIOS> TR_PEND_USUARIOS { get; set; }
        public virtual DbSet<TR_PENDIENTE_CODIGO> TR_PENDIENTE_CODIGO { get; set; }
        public virtual DbSet<TR_PENDIENTE_PROD> TR_PENDIENTE_PROD { get; set; }
        public virtual DbSet<TR_SORTEOS> TR_SORTEOS { get; set; }
        public virtual DbSet<TR_VENTAS_POS> TR_VENTAS_POS { get; set; }
        public virtual DbSet<TR_VENTAS_POS_IMPUESTOS> TR_VENTAS_POS_IMPUESTOS { get; set; }
        public virtual DbSet<TR_VENTAS_POS_PAGOS> TR_VENTAS_POS_PAGOS { get; set; }
        public virtual DbSet<C0NE_TIME_SCRIPT_EVENTS_HISTORY> C0NE_TIME_SCRIPT_EVENTS_HISTORY { get; set; }
        public virtual DbSet<ESTRUC_SIS> ESTRUC_SIS { get; set; }
        public virtual DbSet<MA_ACTUALIZACION_INVENTARIO_PENDIENTE> MA_ACTUALIZACION_INVENTARIO_PENDIENTE { get; set; }
        public virtual DbSet<MA_ACTUALIZACION_INVENTARIO_PENDIENTE_FOOD> MA_ACTUALIZACION_INVENTARIO_PENDIENTE_FOOD { get; set; }
        public virtual DbSet<MA_CAJA_BITACORA> MA_CAJA_BITACORA { get; set; }
        public virtual DbSet<MA_CONCEPTOS> MA_CONCEPTOS { get; set; }
        public virtual DbSet<MA_CONSECUTIVOS> MA_CONSECUTIVOS { get; set; }
        public virtual DbSet<MA_CONTORNOS> MA_CONTORNOS { get; set; }
        public virtual DbSet<MA_CORRELATIVO_RETENCION> MA_CORRELATIVO_RETENCION { get; set; }
        public virtual DbSet<MA_DENOMINACIONES> MA_DENOMINACIONES { get; set; }
        public virtual DbSet<MA_HABLADORES_BITACORA> MA_HABLADORES_BITACORA { get; set; }
        public virtual DbSet<MA_HISTORICO_IMPUESTO> MA_HISTORICO_IMPUESTO { get; set; }
        public virtual DbSet<MA_IMPRESORA_DEPARTAMENTO> MA_IMPRESORA_DEPARTAMENTO { get; set; }
        public virtual DbSet<MA_IMPRESORA_GRUPO> MA_IMPRESORA_GRUPO { get; set; }
        public virtual DbSet<MA_IMPRESORA_SUBGRUPO> MA_IMPRESORA_SUBGRUPO { get; set; }
        public virtual DbSet<MA_KDS_DEPARTAMENTO> MA_KDS_DEPARTAMENTO { get; set; }
        public virtual DbSet<MA_KDS_GRUPO> MA_KDS_GRUPO { get; set; }
        public virtual DbSet<MA_KDS_SUBGRUPO> MA_KDS_SUBGRUPO { get; set; }
        public virtual DbSet<MA_PRODUCTOS_COMPUESTOS> MA_PRODUCTOS_COMPUESTOS { get; set; }
        public virtual DbSet<MA_SYSTABLAS> MA_SYSTABLAS { get; set; }
        public virtual DbSet<MA_VENDEDORES_GRUPOS_COMISION> MA_VENDEDORES_GRUPOS_COMISION { get; set; }
        public virtual DbSet<MA_VENTAS> MA_VENTAS { get; set; }
        public virtual DbSet<MA_VENTAS_IMPUESTOS> MA_VENTAS_IMPUESTOS { get; set; }
        public virtual DbSet<MA_VENTAS_RETENCIONES> MA_VENTAS_RETENCIONES { get; set; }
        public virtual DbSet<TblUsuarioDev> TblUsuarioDev { get; set; }
        public virtual DbSet<TMP_ACT_HBL> TMP_ACT_HBL { get; set; }
        public virtual DbSet<TMP_LOG_MA_PAGOS> TMP_LOG_MA_PAGOS { get; set; }
        public virtual DbSet<TMP_PRODXPROV> TMP_PRODXPROV { get; set; }
        public virtual DbSet<TR_CIERRE_POS> TR_CIERRE_POS { get; set; }
        public virtual DbSet<TR_CIERRE_POS_CAMBIO> TR_CIERRE_POS_CAMBIO { get; set; }
        public virtual DbSet<TR_CONSUMO_TEMP> TR_CONSUMO_TEMP { get; set; }
        public virtual DbSet<TR_DENOMINA_SERIALES_TEMP> TR_DENOMINA_SERIALES_TEMP { get; set; }
        public virtual DbSet<TR_DENOMINA_TEMP> TR_DENOMINA_TEMP { get; set; }
        public virtual DbSet<TR_DEVOLUCION> TR_DEVOLUCION { get; set; }
        public virtual DbSet<TR_PEND_BANCOS> TR_PEND_BANCOS { get; set; }
        public virtual DbSet<TR_PEND_CLIENTES> TR_PEND_CLIENTES { get; set; }
        public virtual DbSet<TR_PEND_PRODUCTOS> TR_PEND_PRODUCTOS { get; set; }
        public virtual DbSet<TR_PEND_VENTAS_VOLUMEN> TR_PEND_VENTAS_VOLUMEN { get; set; }
        public virtual DbSet<TR_PENDIENTE_PRODUCTOS_COMPUESTOS> TR_PENDIENTE_PRODUCTOS_COMPUESTOS { get; set; }
        public virtual DbSet<TR_REPORTES> TR_REPORTES { get; set; }
        public virtual DbSet<TR_SITIO_RESERVAR> TR_SITIO_RESERVAR { get; set; }
    }
}
